### PR TITLE
Move from startOrReload to start to prevent unnecessary restarts.

### PR DESCRIPTION
**Pull request by MorganEPatch**
Basically the same as https://github.com/osuosl-cookbooks/timesync/pull/16, but apparently replicated in this cookbook.

### CODE REVIEW

**Review by fahlmant — CHANGES_REQUESTED** [review]
There needs to be some way to test this so that we know it works.

**Comment by MorganEPatch** [comment]
If you have any ideas how to test it, I'm definitely open, but I don't think we've figured out any good ideas.

**Review by ramereth — APPROVED** [review]

**Comment by MorganEPatch** [comment]
!bump minor

**Comment by osuosl-manatee** [comment]
Jenkins has merged this PR into `master` and has automatically performed a minor-level version bump to v1.1.0.  Have a nice day!

**Pull request merged**
