### PR TITLE
Provide separate install and run actions for finer control.

### PR DESCRIPTION
**Pull request by MorganEPatch**
While working on cleaning up this and the timesync cookbook, I realized that we're ultimately calling "pm2 start" twice, once in that cookbook and once in this. So my first step in resolving this is to split this cookbook into an "install" action, which creates the user/group, installs/upgrades npm, pulls the project from git, and creates the PM2 config; and a "run" action, which starts the PM2 application and saves the deploy script.

### CODE REVIEW

**Review by fahlmant — CHANGES_REQUESTED** [review]
@LyonesGamer Pleas copy the Rakefile from a newer, updated cookbook, like osl-apache, and run `rake`. This will show you most if not all the problems that travis checks for.

**Comment by MorganEPatch** [comment]
@fahlmant Yeah, @jldugger and I have been working together to clean this up and get it fixed.

**Review by fahlmant — CHANGES_REQUESTED** [review]
`.kitchen.list.yml` shouldn't be commited.

**Comment by MorganEPatch** [comment]
Oops.

**Review by fahlmant — CHANGES_REQUESTED** [review]
The spec test should also check if the package is installed. I think the convention is for everything the recipe does, the chefspec test should check.

**Review by fahlmant — CHANGES_REQUESTED** [review]
Kitchen is failing

**Comment by fahlmant** [comment]
@LyonesGamer Any update on this?h

**Pull request closed without merging**
